You have received **customer** and **order details** in the form of **Excel sheets**. Here’s how the **customer details** looks like : 

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/customer_details-01.png)


Here’s how the **order details** looks like : 
![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/03-order-details.png)


---------------------------

**Task - 1 :**

Let’s look at the first record in the **Orders** sheet. The **Sales Amount** for the product **Bush Somerset Collection Bookcase** purchased by customer_id **AA-10315** is **2000**. The total **quantity** sold is **2**. 

How would you calculate the **unit price** in Excel?


You’ll write a formula referring the **cell addresses** of **2000** and **2** and the outcome would look something like below : 

![](https://raw.githubusercontent.com/mentorskool/python-essentials/main/Module-6-PY-Learning-4/imgs/var_intro_sample_img1.png)


What’s the **cell address** here? It is nothing but a way for Excel or rather your computer to **memorize the values** **2000** and **2**. Also, you can change the values of the cell addresses **K2** and **L2** to anything you want.  In short, Its value **varies**. Hence, it is called a **variable**

How would you achieve the above task in **Python**?

In [ ]:
# First, let's try doing this in the simplest way. Divide 2000 by 2 
# In order to see the output execute this cell by clicking on the play button or hit Shift + Enter

2000/2

1000.0

In [ ]:
# Next, let’s see how to fetch the same output by using variables - 
# Store the values in two variable named sales and quantity

sales = 2000
quantity = 2

# Divide sales by quantity and store in a new variable called output

output = sales/quantity

# Let's see what does the variable output stores

output 

1000.0

In [ ]:
# Also you can use print and put the variable inside round brackets, remove'#' and run the code. This '#' symbol is nothing but a way to ensure the code following this gets ignored by Python compiler. 
# Use it freely to add comments to your code as we have done here

# print(output)

**Advantage with variables?**

You can **change** the **values** to **anything you want**

---------------------------

**Task - 2 :** 

Set value of sales to **5000** and quantity to **100** and use the **print** function to show output

In [ ]:
# Write your code below



------------------------

**Did you notice?**

We did a **division operation** here on the two values. Similarly, we can do any other math operations. Let's solve another scenario below.

**Task - 3 :**

Given the **sales amount** of **2000**, **quantity** of **2** and **profit** of **500** (Check snapshot of **order details** above), What will be the **unit cost** at which the product was sold? (**Ignore discount** for this task)

In [ ]:
# Let's store profit value in a new variable

profit = 500

# Think what will you do in Excel to calculate the unit cost of product 
# We will do something similar in Python

output = sales-profit/quantity
print(output)

1750.0


**Note :** 

* Did you observe that we **didn't need to declare** sales and quantity variable again in the above cell because it **picked up the value** from the variables already **declared** and **assigned** earlier. (This helps ensure values are **assigned at a single place** and used wherever needed)

* Also, observe that the value of **output** variable which was **1000.0** earlier got replaced by **1750.0**. This shows that **variables can be overwritten** by new operations. If you wish to retain value of earlier variable, try giving a **different variable name** like **output1** or something

**Hold On!**

* Did you notice the value of **output** variable above?
* Do you think it is correct?
* Revisit your calculation carefully. The **unit cost** should be **750.0**
* What went wrong?

**Nothing much!** Just recall the **BODMAS rule** you studied at school. The **use of parantheses is incorrect here**. 

**Python** also uses a similar type of rule known as **PEMDAS**.

  * P – Parentheses
  * E – Exponentiation
  * M – Multiplication
  * D – Division
  * A – Addition
  * S – Subtraction

In [ ]:
#Let's do it with proper parentheses
output = (sales-profit)/quantity #as discussed variables are already declared ,so we can directly use them now
print(output)

750.0


-----------------------
**Task - 4 :**

Given that **2 units** the product **Bush Somerset Collection Bookcase** was sold at **2000** after applying a discount of **2.5%**, calculate the **unit price** of the product **before** discount was applied 

In [ ]:
# Write your code below 


**Before we close :**

Now, you know how useful variables are in Python.
However, it is important to keep in mind some **ground rules** on how to **name your variables**. 

Spend some time going through this article to understand **naming rules for variables** : [here](https://www.w3schools.com/python/gloss_python_variable_names.asp)   